# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - name: Deliver file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.MOIM_SSH_HOST }}
        username: ${{ secrets.MOIM_SSH_USERNAME }}
        key: ${{ secrets.MOIM_SSH_KEY }}
        port: ${{ secrets.MOIM_SSH_PORT }}
        source: "build/libs/*.jar"
        target: "source"
        rm: true
    - name: Deploy new version of server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MOIM_SSH_HOST }}
        username: ${{ secrets.MOIM_SSH_USERNAME }}
        key: ${{ secrets.MOIM_SSH_KEY }}
        port: ${{ secrets.MOIM_SSH_PORT }}
        script: |
          SOURCE_DIR=source/build/libs
          FILE_NAME=`find $SOURCE_DIR/*.jar -printf "%f\n"`
          PID=`ps -ef | grep java | grep api | grep -v "bash -c" | awk '{print $2}'`
          
          echo "Old version of app is currently running on $PID." 
          echo "Filename of new version is $FILE_NAME." 
          echo "Directory: $SOURCE_DIR"
          
          if [ -z "$PID" ]; then 
            echo "No process found." 
          else 
            echo "Terminating $PID..." 
            kill $PID 
          fi
          
          java -jar $SOURCE_DIR/$FILE_NAME > /dev/null 2>&1 &